# -*- coding: utf-8 -*-
"""currency converter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h8h-p0z6LrueePScKSOgqVo_aVyR1yth
"""

def display_menu():
  print("1. Convert USD to Euro(EUR)")
  print("2. Convert USD to British Pound Sterling(GBP)")
  print("3. Convert USD to Japenese Yen(JPY)")
  print("4. Convert USD to Canadian Dollar(CAD)")
  print("5. Convert USD to India(INR)")
  print("6. Exit")

def USD_to_EUR(value):
  return value*0.94
def USD_to_GBP(value):
  return value*0.79
def USD_to_JPY(value):
  return value*113
def USD_to_CAD(value):
  return value*1.33
def USD_to_INR(value):
  return value*83.24

while True:
  display_menu()
  choice=int(input())
  if choice==6:
    print("Thank you!")
    break
  else:
    amount=float(input("Enter an amount in US dollars: "))
    if choice==1:
      print(amount,"USD",USD_to_EUR(amount),"Euro")
    elif choice==2:
      print(amount,"USD",USD_to_GBP(amount),"GBP")
    elif choice==3:
      print(amount,"USD",USD_to_JPY(amount),"JPY")
    elif choice==4:
      print(amount,"USD",USD_to_CAD(amount),"CAD")
    elif choice==5:
        print(amount,"USD",USD_to_INR(amount),"INR")